POST http://localhost:3000/api/hdAndHdct
Content-Type: application/json

{
    "don_hang_id": "66984db1626da276edaab27e"
}

###
GET http://localhost:3000/api/donhang/66812a5658f41685a1eae74d?role=false
Content-Type: application/json


###
PUT http://localhost:3000/api/UpdateSocketId
Content-Type: application/json

{
    "id": "66812ad058f41685a1eae751",
    "socket": 
} 

###
POST http://localhost:3000/api/donhang/66812a5658f41685a1eae74d
Content-Type: application/json

{  
  {
    "phuong_thuc_thanh_toan": "Thanh toán khi nhận hàng",
    "dia_chi_giao_hang": "123 Đường ABC, Quận XYZ, Thành phố HCM",
    "ghi_chu": "Giao hàng vào buổi sáng nếu được",
    "tinh_trang": "Chưa xử lý"
}
}


###
POST http://localhost:3000/api/donhang/66812a5658f41685a1eae74d
Content-Type: application/json

 {
    "phuong_thuc_thanh_toan": "Thanh toán khi nhận hàng",
    "dia_chi_giao_hang": "123 Đường ABC, Quận XYZ, Thành phố HCM",
    "ghi_chu": "Giao hàng vào buổi sáng nếu được",
    "tinh_trang": "Chưa xử lý"
}