POST http://localhost:3000/api/gioHangVaChiTiet
Content-Type: application/json

{
  "nguoi_dung_id": "66812a5658f41685a1eae74d",
  "noi_that_id": "667fbc80d8ea08508373ec2b",
  "so_luong": 200,
  "gia": 150000
}


###
GET http://localhost:3000/api/gioHangCT/66812a5658f41685a1eae74d
Content-Type: application/json

{
    "nguoi_dung_id": "66812a5658f41685a1eae74d",
    "trang_thai": 1
}



###
PUT http://localhost:3000/api/donhang/6683ea0d67aa8fa076df6cc5/trangthai
Content-Type: application/json

{
    "trangthai": "KKK",
    "role": true
} 

###
PUT http://localhost:3000/api/donhang/6683ea0d67aa8fa076df6cc5/trangthai
Content-Type: application/json

{
   
    "trangthai": "cập nhật trạng thái",
    "tinh_trang": "thanh toán rồi"
}
