POST http://localhost:3000/api/gioHang
Content-Type: application/json

{
    "nguoi_dung_id": "667dbfcbe8426273772ec45d",
    "tong_gia": 0,
    "trang_thai": 1
}

###
GET http://localhost:3000/api/danhMuc
Content-Type: application/json

# {
#     "nguoi_dung_id": "user123456",
#     "trang_thai": 1
# }



###
POST http://localhost:3000/api/gioHangCT
Content-Type: application/json

{
    "gio_hang_id": "667e7cbea9497ff0545be1bb",
    "noi_that_id": "667e36f08f4d1e9fb86b01b8",
    "so_luong": 2,
    "gia": 200
}


###
PUT http://localhost:3000/api/gioHangCT/667e790d10c5c8c8dc05334a
Content-Type: application/json

{
   
    "so_luong": 7
}
